auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: C:/loki/data
  ring:
    kvstore:
      store: inmemory

storage_config:
  boltdb_shipper:
    active_index_directory: C:/loki/index
    cache_location: C:/loki/boltdb-cache
  filesystem:
    directory: C:/loki/chunks

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  allow_structured_metadata: false  # Critical fix for v3.x
  reject_old_samples: true
  reject_old_samples_max_age: 168h

compactor:
  working_directory: C:/loki/compactor

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1